name: Terraform with Akeyless

on:
  workflow_dispatch:

jobs:

  terraform:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Terraform Init
      run: terraform init
