name: Terraform with Akeyless

on:
  workflow_dispatch:

jobs:

  terraform:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Get OIDC Token
        run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          JWT=$(echo $OIDC_TOKEN | jq -j '.value')
          echo "JWT=$JWT" >> $GITHUB_ENV # Store the JWT as an environment variable


      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        env:
          TF_VAR_jwt: ${{ env.JWT }}
        run: terraform plan

      - name: Terraform apply
        env:
          TF_VAR_jwt: ${{ env.JWT }}
        run: terraform apply -auto-approve